title: "LING 539 Project"
author: "Song Yi Kim"
email: "songyikim@arizona.edu"
description: "A tutorial on measuring vowel quality using Python (formants and duration)"
theme: minima
baseurl: "/ling-539-project"
url: "https://songyi30.github.io"

markdown: kramdown

# Build settings
plugins:
  - jekyll-feed
